apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: fpaho
  labels:
    app: app
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  minReadySeconds: 20
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: feature-toggle
        - secretRef:
            name: db-secret
        name: app-deployment
        image: harbor.dev.afsmtddso.com/fpaho-harbor-project/app@sha256:e3ada55c2953745fa98a5f22051639d76b624f3a6c822e1ec65d0ef4df6f4ec5
        ports:
        - containerPort: 5000
